/**
 * Generated by scripts/build-topsites-tier.mjs from data/top_sites.filtered.csv.
 * Starter seed only: keep the runtime code stable while the vetted Tranco/CrUX
 * export grows behind the same build-time interface.
 */
export const TOP_SITE_TIER_ENTRIES = [
  { domain: "adobe.com" },
  { domain: "amazon.com" },
  { domain: "apple.com" },
  { domain: "atlassian.com" },
  { domain: "auth0.com" },
  { domain: "dropbox.com" },
  { domain: "github.com" },
  { domain: "google.com" },
  { domain: "icloud.com" },
  { domain: "linkedin.com" },
  { domain: "login.microsoftonline.com" },
  { domain: "microsoft.com" },
  { domain: "mozilla.org" },
  { domain: "office.com" },
  { domain: "okta.com" },
  { domain: "paypal.com" },
  { domain: "salesforce.com" },
  { domain: "shopify.com" },
  { domain: "slack.com" },
  { domain: "stackoverflow.com" },
  { domain: "stripe.com" },
  { domain: "wikipedia.org" },
  { domain: "youtube.com" },
  { domain: "zoom.us" },
] as const;
