/**
 * Generated by scripts/build-topsites-tier.mjs from data/top_sites.filtered.csv.
 * Starter seed only: keep the runtime code stable while the vetted Tranco/CrUX
 * export grows behind the same build-time interface.
 */
export const TOP_SITE_TIER_DOMAINS = [
  "adobe.com",
  "amazon.com",
  "apple.com",
  "atlassian.com",
  "auth0.com",
  "dropbox.com",
  "github.com",
  "google.com",
  "icloud.com",
  "linkedin.com",
  "login.microsoftonline.com",
  "microsoft.com",
  "mozilla.org",
  "office.com",
  "okta.com",
  "paypal.com",
  "salesforce.com",
  "shopify.com",
  "slack.com",
  "stackoverflow.com",
  "stripe.com",
  "wikipedia.org",
  "youtube.com",
  "zoom.us",
] as const;
